
version: 2

models:
    - name: game_titles
      description: "Raw title data"
      columns:
          - name: game_title_key
            description: "The primary key for this table - specifies game"
            tests:
                - unique
                - not_null
    - name: draft_data
      description: "this model houses the quartiled player data for draft night"  

sources:
  - name: source
    tables:
      - name: game_titles
        description: "Stores different games across portfolio for tournaments"
        columns:
          - name: game_title_key
          - name: game_title_name
      - name: lifetime_gameplay
        description: "Bulk api pull for overall data of players, data is at
        point in time"
      - name: tournament_roster
        description: "Weekly available roster for tournaments"
      - name: tournament_rules
        description: "Weekly decided ruleset for specified tournament"
      - name: tournament_teams
        description: "Drafted teams and captains"
      - name: tournament_weeks
        description: "Stores timelines for when tournaments are played in epoch"
      - name: user_attributes
        description: "User attribute data used for marketing and analytics"
      - name: users
        description: "Represents user at sign-up"
      - name: tournament_gameplay
        description: "Output of get_games.py"
